# 默认配置文件
spring:
  application:
    name: platform-default

# 数据库配置
database:
  url: jdbc:mysql://localhost:3306/platform
  username: root
  password: root

# Redis配置
redis:
  host: localhost
  port: 6379

# RabbitMQ配置
rabbitmq:
  host: localhost
  port: 5672
  username: admin
  password: admin

# 监控配置
monitoring:
  prometheus:
    enabled: true
    endpoint: http://localhost:9090
  grafana:
    enabled: true
    endpoint: http://localhost:3000 