global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'platform-service-registry'
    static_configs:
      - targets: ['localhost:8761']

  - job_name: 'platform-config-server'
    static_configs:
      - targets: ['localhost:8888']

  - job_name: 'platform-api-gateway'
    static_configs:
      - targets: ['localhost:8080']

  - job_name: 'platform-deployment-engine'
    static_configs:
      - targets: ['localhost:8081']

  - job_name: 'platform-resource-manager'
    static_configs:
      - targets: ['localhost:8082']

  - job_name: 'platform-monitor'
    static_configs:
      - targets: ['localhost:8083']

  - job_name: 'platform-decision-engine'
    static_configs:
      - targets: ['localhost:8084'] 