server:
  port: 8888

spring:
  application:
    name: platform-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xie-yingshuo/MasterProject.git
          default-label: main
          search-paths: config
        native:
          search-locations: classpath:/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always 